version: '3'
services:
  django:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    image: 'robotics-web-backend-1:latest'
    container_name: django
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresql
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ../backend:/app
    depends_on:
      - postgresql
    networks:
      - app-network

  vue:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    image: 'robotics-web-frontend-1:latest'
    container_name: vue
    restart: unless-stopped
    env_file: .env
    environment:
      - BACKEND_HOST=django
    ports:
    - 8080:80
    volumes:
    - ../frontend:/app
    - /app/node_modules
    depends_on:
      - django
    networks:
      - app-network
  
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=$DB_USER
      - POSTGRESQL_PASSWORD=$DB_PASSWORD
      - POSTGRESQL_DATABASE=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: