name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: copy env
      run: cp .env.example .env
    - name: Build the Docker
      run: docker-compose build
